PST-07 UI - Add Profile Pic avatar along with dropdown arrow. Dropdown having profile and logout
phanisofttech/student-portal pull request #2
Opened 2024-06-26 15:32 UTC by suneel-katta

PST-07 UI - Add Profile Pic avatar along with dropdown arrow. Dropdown having profile and logout

2024-06-26 15:39 UTC, phanisofttech requested changes

2024-06-26 15:39 UTC, phanisofttech commented on src/main/webapp/student_navigation_bar.html
> +
Remove extra lines only keep one lilne

2024-06-26 15:39 UTC, phanisofttech commented on src/main/webapp/student_navigation_bar.html
> +
Add comment with description

<!-- Profile Avatar with dropdown -->

2024-06-26 15:39 UTC, phanisofttech commented on src/main/webapp/student_navigation_bar.html
> +
Remove extra spaces only keep one space

2024-06-27 14:23 UTC, suneel-katta commented
Changes altered @phanisofttech

2024-06-27 14:52 UTC, suneel-katta commented on src/main/webapp/student_navigation_bar.html
> +
altered

2024-06-27 14:53 UTC, suneel-katta commented on src/main/webapp/student_navigation_bar.html
> +
altered

2024-06-27 14:53 UTC, suneel-katta commented on src/main/webapp/student_navigation_bar.html
> +
altered

2024-06-27 14:54 UTC, merged